parameters:
    git:
        owner: zeeleluc
        repositories:
            -   cryptopunks-pixels
            -   xrplmarketplace
            -   hasmints.com
            -   richlists
            -   nft-collection-assembling-1
            -   solana-burn-mint