opensource:
    host: 'hasmints.%ext%'
    path: /opensource
    controller: App\Controller\OpenSourceController::index

team:
    host: 'hasmints.%ext%'
    path: /team
    controller: App\Controller\TeamController::index

homepage:
    host: 'hasmints.%ext%'
    path: /
    controller: App\Controller\HomeController::index
    defaults:
        template: default/homepage.html.twig

homepage_www:
    host: 'www.hasmints.%ext%'
    path: /
    controller: App\Controller\HomeController::index
    defaults:
        template: default/homepage.html.twig

controllers:
    resource:
        path: '../src/Controller/'
        namespace: App\Controller
    type: attribute
    prefix: /
    requirements:
