portfolio:
    host: '{subdomain}.hasmints.{domain}'
    path: /
    controller: App\Controller\PortfolioController::index
    requirements:
        subdomain: luc|diana
        domain: local|com

opensource:
    host: 'hasmints.%ext%'
    path: /opensource
    controller: App\Controller\OpenSourceController::index

homepage:
    host: 'hasmints.%ext%'
    path: /
    controller: App\Controller\HomeController::index
    defaults:
        template: default/homepage.html.twig

homepage_www:
    host: 'www.hasmints.%ext%'
    path: /
    controller: App\Controller\HomeController::index
    defaults:
        template: default/homepage.html.twig

controllers:
    resource:
        path: '../src/Controller/'
        namespace: App\Controller
    type: attribute
    prefix: /
    requirements:
